from pandas import Series, DataFrame
data={'语文':[68,95,98,90,80],'数学':[65,76,86,88,90],
'英语':[30,98,88,77,90]}
df1=DataFrame(data,index=['张飞','关羽','刘备','典韦','许褚'],
columns=['语文','数学','英语'])
print(df1.describe())
print('打印成绩表:','\n',df1)
#每科目平均成绩
average=df1.mean(0)
print(average)
#每科目最小成绩
min_everysubject=df1.min(0)
print(min_everysubject)
#每个人最小成绩
min_everyone=df1.min(1)
print(min_everyone)
#每科目最大成绩
max_everysubject=df1.max(0)
print(max_everysubject)
#每个人最大成绩
max_everyone=df1.max(1)
print(max_everyone)
#每科目方差
var_everysubject=df1.var(1)
print(var_everysubject)
#每科目标准差
std_everysubject=df1.std(1)
print(std_everysubject)
#每个人总成绩排序
df2=DataFrame(df1.sum(1),columns=['总成绩'])
print(df2.sort_values(by='总成绩'))
